steps:
  # 1. 백엔드 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/docker-repo/medilogis-ai-backend', './backend']
  
  # 2. 백엔드 이미지 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/docker-repo/medilogis-ai-backend']
    
  # 3. 백엔드 Cloud Run 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'medilogis-ai-backend'
      - '--image'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/docker-repo/medilogis-ai-backend'
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '5001'

  # 4. 프론트엔드 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/docker-repo/medilogis-ai-frontend', './frontend']
    
  # 5. 프론트엔드 이미지 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/docker-repo/medilogis-ai-frontend']

  # 6. 프론트엔드 Cloud Run 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'medilogis-ai-frontend'
      - '--image'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/docker-repo/medilogis-ai-frontend'
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'

images:
  - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/docker-repo/medilogis-ai-backend'
  - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/docker-repo/medilogis-ai-frontend'

options:
  logging: CLOUD_LOGGING_ONLY
