name: Debug Server Status

on:
  push:
    branches:
      - main 

env:
  PROJECT_ID: wayn-492112
  REGION: asia-northeast3
  REPO_NAME: wayn-ai-repo
  GCE_INSTANCE: "wayn-server"
  GCE_ZONE: "asia-northeast3-a"

jobs:
  debug:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/966609209672/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions@wayn-492112.iam.gserviceaccount.com'

      - name: Deploy to GCE
        run: |
          gcloud compute ssh wayn-ai@${{ env.GCE_INSTANCE }} --zone=${{ env.GCE_ZONE }} --command="
            echo '--- DISK SPACE ---'
            df -h
            echo '--- DOCKER CONTAINERS ---'
            docker ps -a
            echo '--- LOGS for medilogis-ai-frontend ---'
            docker logs medilogis-ai-frontend
            echo '--- LOGS for mediedu-ai-frontend ---'
            docker logs mediedu-ai-frontend
          "
