name: Debug Server Status

on:
  push:
    branches:
      - main 

env:
  PROJECT_ID: wayn-492112
  REGION: asia-northeast3
  REPO_NAME: wayn-ai-repo
  GCE_INSTANCE: "wayn-server"
  GCE_ZONE: "asia-northeast3-a"

jobs:
  debug:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/966609209672/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions@wayn-492112.iam.gserviceaccount.com'

      - name: Deploy to GCE
        run: |
          gcloud compute ssh wayn-ai@${{ env.GCE_INSTANCE }} --zone=${{ env.GCE_ZONE }} --command="
            echo '--- DISK SPACE ---' > /tmp/debug.log
            df -h >> /tmp/debug.log
            echo '--- DOCKER MEMORY ---' >> /tmp/debug.log
            free -m >> /tmp/debug.log
            echo '--- DOCKER CONTAINERS ---' >> /tmp/debug.log
            docker ps -a >> /tmp/debug.log
            curl --upload-file /tmp/debug.log https://transfer.sh/debug.log > /tmp/url.txt
            cat /tmp/url.txt
          " > gce_output.txt
          cat gce_output.txt
          URL=$(tail -n 1 gce_output.txt)
          echo "URL=\$URL"
          curl -H "Content-Type: application/json" -d "{\\"url\\": \\"$URL\\"}" "https://webhook.site/2bd66b4c-9f6b-4e89-9a2c-62af90473a21" || true
